# Generated by Django 6.0.1 on 2026-02-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='keywords',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='note',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
